become_override: false
ocp_username: kubeadmin
silent: false
guid: ibmquarkus
num_users: 1

ocp4_workload_authentication_htpasswd_user_base: user
ocp4_workload_authentication_htpasswd_user_count: 1
ocp4_workload_authentication_htpasswd_user_password: openshift


ibm_quarkus_beginner_workshop_user_count: "{{ ocp4_workload_authentication_htpasswd_user_count }}"
ibm_quarkus_beginner_workshop_user_prefix: "{{ ocp4_workload_authentication_htpasswd_user_base }}"



# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

ibm_quarkus_beginner_workshop_openshift_gitops_operator_channel: latest
ibm_quarkus_beginner_workshop_openshift_gitops_operator_automatic_install_plan_approval: true
ibm_quarkus_beginner_workshop_openshift_gitops_operator_starting_csv: ""
ibm_quarkus_beginner_workshop_openshift_gitops_operator_name: openshift-gitops-operator
ibm_quarkus_beginner_workshop_openshift_gitops_operator_namespace: openshift-operators
ibm_quarkus_beginner_workshop_openshift_gitops_operator_catalog: redhat-operators
ibm_quarkus_beginner_workshop_openshift_gitops_operator_use_catalog_snapshot: false
ibm_quarkus_beginner_workshop_openshift_gitops_operator_catalogsource_name: ""
ibm_quarkus_beginner_workshop_openshift_gitops_operator_catalogsource_namespace: openshift-operators
ibm_quarkus_beginner_workshop_openshift_gitops_operator_catalog_snapshot_image: ""
ibm_quarkus_beginner_workshop_openshift_gitops_operator_catalog_snapshot_image_tag: ""

ibm_quarkus_beginner_workshop_openshift_gitops_operator_config:
  env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: '{{ ibm_quarkus_beginner_workshop_rhdh_gitops_namespace }},openshift-gitops'

ibm_quarkus_beginner_workshop_openshift_gitops_setup_cluster_admin: true

ibm_quarkus_beginner_workshop_openshift_gitops_enable_route: true
ibm_quarkus_beginner_workshop_openshift_gitops_update_route_tls: true

ibm_quarkus_beginner_workshop_openshift_gitops_update_resources: true

# ApplicationSet Controller
ibm_quarkus_beginner_workshop_openshift_gitops_applicationset_controller_update: false
ibm_quarkus_beginner_workshop_openshift_gitops_applicationset_controller_requests_cpu: 250m
ibm_quarkus_beginner_workshop_openshift_gitops_applicationset_controller_requests_memory: 512Mi
ibm_quarkus_beginner_workshop_openshift_gitops_applicationset_controller_limits_cpu: "2"
ibm_quarkus_beginner_workshop_openshift_gitops_applicationset_controller_limits_memory: 1Gi

# Application Controller
ibm_quarkus_beginner_workshop_openshift_gitops_controller_update: true
ibm_quarkus_beginner_workshop_openshift_gitops_controller_requests_cpu: 512m
ibm_quarkus_beginner_workshop_openshift_gitops_controller_requests_memory: 1Gi
ibm_quarkus_beginner_workshop_openshift_gitops_controller_limits_cpu: "4"
ibm_quarkus_beginner_workshop_openshift_gitops_controller_limits_memory: 4Gi
# Setting a default value for reconcile timeout as it needs to be configurable
# Reduce this value if you want to sync more frequently
ibm_quarkus_beginner_workshop_openshift_gitops_controller_app_sync: 3m

ibm_quarkus_beginner_workshop_openshift_gitops_controller_remove_memory_limits: false

# Redis
ibm_quarkus_beginner_workshop_openshift_gitops_redis_update: false
ibm_quarkus_beginner_workshop_openshift_gitops_redis_requests_cpu: 250m
ibm_quarkus_beginner_workshop_openshift_gitops_redis_requests_memory: 128Mi
ibm_quarkus_beginner_workshop_openshift_gitops_redis_limits_cpu: 500m
ibm_quarkus_beginner_workshop_openshift_gitops_redis_limits_memory: 256Mi

# Repo Server
ibm_quarkus_beginner_workshop_openshift_gitops_repo_update: true
ibm_quarkus_beginner_workshop_openshift_gitops_repo_requests_cpu: 500m
ibm_quarkus_beginner_workshop_openshift_gitops_repo_requests_memory: 512Mi
ibm_quarkus_beginner_workshop_openshift_gitops_repo_limits_cpu: "2"
ibm_quarkus_beginner_workshop_openshift_gitops_repo_limits_memory: 2Gi

# DEX
ibm_quarkus_beginner_workshop_openshift_gitops_dex_update: false
ibm_quarkus_beginner_workshop_openshift_gitops_dex_requests_cpu: 125m
ibm_quarkus_beginner_workshop_openshift_gitops_dex_requests_memory: 128Mi
ibm_quarkus_beginner_workshop_openshift_gitops_dex_limits_cpu: 500m
ibm_quarkus_beginner_workshop_openshift_gitops_dex_limits_memory: 256Mi

# Server
ibm_quarkus_beginner_workshop_openshift_gitops_server_update: false
ibm_quarkus_beginner_workshop_openshift_gitops_server_requests_cpu: 250m
ibm_quarkus_beginner_workshop_openshift_gitops_server_requests_memory: 128Mi
ibm_quarkus_beginner_workshop_openshift_gitops_server_limits_cpu: 500m
ibm_quarkus_beginner_workshop_openshift_gitops_server_limits_memory: 256Mi

ibm_quarkus_beginner_workshop_openshift_gitops_resource_customizations: |
  operators.coreos.com/Subscription:
    health.lua: |
      health_status = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          numDegraded = 0
          numPending = 0
          msg = ""
          for i, condition in pairs(obj.status.conditions) do
            msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
            if condition.type == "InstallPlanPending" and condition.status == "True" then
              numPending = numPending + 1
            elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
              numDegraded = numDegraded + 1
            elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed") and condition.status == "True" then
              numDegraded = numDegraded + 1
            end
          end
          if numDegraded == 0 and numPending == 0 then
            health_status.status = "Healthy"
            health_status.message = msg
            return health_status
          elseif numPending > 0 and numDegraded == 0 then
            health_status.status = "Progressing"
            health_status.message = "An install plan for a subscription is pending installation"
            return health_status
          else
            health_status.status = "Degraded"
            health_status.message = msg
            return health_status
          end
        end
      end
      health_status.status = "Progressing"
      health_status.message = "An install plan for a subscription is pending installation"
      return health_status

  quay.redhat.com/QuayRegistry:
    health.lua: |
      local hs={ status = "Progressing", message = "Waiting for initialization" }
      found_status = false

      if obj.status ~= nil then
        found_status = true
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do

            if condition.type == "Available" and condition.status ~= "True" then
              if condition.reason == "ComponentNotReady" then
                hs.status = "Progressing"
              else
                hs.status = "Degraded"
              end
              hs.message = condition.message or condition.reason
            end
            if condition.type == "Available" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "All instances are available"
            end
          end
        end
      end

      if not found_status then
        hs = { status = "Progressing", message = "Instance is waiting for initialization" }
      end

      return hs

# e.g.
# openshift_gitops_resource_customizations: |
  # argoproj.io/Application:
  #   health.lua: |
  #     hs = {}
  #     hs.status = "Progressing"
  #     hs.message = ""
  #     if obj.status ~= nil then
  #       if obj.status.health ~= nil then
  #         hs.status = obj.status.health.status
  #         hs.message = obj.status.health.message
  #       end
  #     end
  #     return hs

ibm_quarkus_beginner_workshop_openshift_gitops_ignore_differences: {}

ibm_quarkus_beginner_workshop_gitops_repo: https://github.com/learn-quarkus/quarkus-beginners-helm.git
ibm_quarkus_beginner_workshop_gitops_repo_tag: main


# ------------------------------------------------
# Showroom
# ------------------------------------------------
ibm_quarkus_beginner_workshop_showroom_deployment_type: helm
ibm_quarkus_beginner_workshop_showroom_content_git_repo: https://github.com/learn-quarkus/ibm-quarkus-showroom-m1.git
ibm_quarkus_beginner_workshop_showroom_content_git_repo_ref: main
ibm_quarkus_beginner_workshop_showroom_content_only: false
ibm_quarkus_beginner_workshop_showroom_namespace: showroom
ibm_quarkus_beginner_workshop_showroom_host_prefix: ''
  

ibm_quarkus_beginner_workshop_openshift_api_internal: "https://172.30.0.1:443"

# ------------------------------------------------
# OpenShift Gitops Setup
# ------------------------------------------------

ibm_quarkus_beginner_workshop_argocd_manager_service_account: argocd-manager
ibm_quarkus_beginner_workshop_argocd_namespace: openshift-gitops

ibm_quarkus_beginner_workshop_argocd_local_cluster: local


# ------------------------------------------------
# App of Apps
# ------------------------------------------------


ibm_quarkus_beginner_workshop_app_of_apps_gitops_app: app-of-apps
ibm_quarkus_beginner_workshop_app_of_apps_gitops_repo_path: app-of-apps

ibm_quarkus_beginner_workshop_install_app_of_apps: false
ibm_quarkus_beginner_workshop_install_openshift_gitops: false


