---
- name: Install Devspace Operator
  ansible.builtin.include_role:
    name: ocp4_workload_openshift_devspaces
  vars:
    ocp4_workload_openshift_devspaces_catalogsource_setup: false
    ocp4_workload_openshift_devspaces_catalogsource_name: devspaces-catalogsource
    ocp4_workload_openshift_devspaces_catalogsource_image: ""
    ocp4_workload_openshift_devspaces_catalogsource_tag: ""
    ocp4_workload_openshift_devspaces_channel: stable
    ocp4_workload_openshift_devspaces_startingcsv: ""
    ocp4_workload_openshift_devspaces_namespace: openshift-devspaces