---

- name: Install OpenShift devspaces operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_name }}"
    install_operator_namespace: "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_namespace }}"
    install_operator_channel: "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_channel }}"
    install_operator_catalog: "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_starting_csv }}"
    install_operator_catalogsource_setup:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_catalogsource_namespace | default('') }}"
    install_operator_catalogsource_image:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_catalog_snapshot_image_tag | default('') }}"
    install_operator_subscription_config:
      "{{ ibm_quarkus_beginner_workshop_openshift_devspaces_operator_config }}"

- name: Create CheCluster for Dev Spaces Namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'che-cluster-ns.yml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_che_result
  until: git_che_result is not failed

- name: Create CheCluster for Dev Spaces
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'che-cluster.yml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_che_result
  until: git_che_result is not failed
