---
- name: Install htpasswd_user role to create htpasswd users
  ansible.builtin.include_role:
    name: ocp4_workload_authentication
  vars:
    ocp4_workload_authentication_idm_type: htpasswd
    ocp4_workload_authentication_admin_user: admin
    ocp4_workload_authentication_htpasswd_admin_password: "{{ common_admin_password }}"
    ocp4_workload_authentication_htpasswd_user_base: "{{ ibm_quarkus_beginner_workshop_user_base }}"
    ocp4_workload_authentication_htpasswd_user_password: "{{ ibm_quarkus_beginner_workshop_htpasswd_user_password }}"
    ocp4_workload_authentication_htpasswd_user_count: "{{ ibm_quarkus_beginner_workshop_user_count | default('1') | int }}"
    ocp4_workload_authentication_remove_kubeadmin: false
    ocp4_workload_authentication_enable_user_info_data: true
