---
- name: Install htpasswd_user role to create htpasswd users
  ansible.builtin.include_role:
    name: ocp4_workload_authentication_htpasswd_user
  vars:
    ocp4_workload_authentication_idm_type: htpasswd
    ocp4_workload_authentication_remove_kubeadmin: true
    ocp4_workload_authentication_htpasswd_admin_password: "{{ common_password }}"
    ocp4_workload_authentication_htpasswd_user_password: "{{ common_password }}"
    ocp4_workload_authentication_htpasswd_user_base: user
    ocp4_workload_authentication_htpasswd_user_count: "{{ num_users }}"
