---
# Implement your Post Workload deployment tasks here
# --------------------------------------------------

# Remove deployer-notification
- name: Remove consolenotifications deployer-notification
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConsoleNotification
    namespace: openshift-console
    name: deployer-notification

# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Workload tasks completed successfully."
  when:
    - not silent | bool
    - not workload_shared_deployment | default(false) | bool

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Software checks completed successfully"
  when:
    - not silent | bool
    - workload_shared_deployment | default(false) | bool
