---

- name: Print ocp4_workload_authentication_htpasswd_user_count Dec3
  ansible.builtin.debug:
    msg: "ocp4_workload_authentication_htpasswd_user_count: {{ ocp4_workload_authentication_htpasswd_user_count }}"


- name: ocp4_workload_authentication_htpasswd_user_password
  ansible.builtin.debug:
    msg: "jaya: {{ ocp4_workload_authentication_htpasswd_user_password }}"

- name: Setup htpasswd authentication
  ansible.builtin.include_tasks: setup_htpasswd.yml

# Leave this as the last task in the playbook.
- name: workload tasks complete
  ansible.builtin.debug:
    msg: "Workload Tasks completed successfully."
  when: not silent | bool
