---

- name: Install Workshop
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
#    - name: "Install DevSpaces"
#      ansible.builtin.include_role:
#        name: ocp4_workload_devspaces
#      vars:
#        ACTION: create
    - name: "Install Workshop"
      ansible.builtin.include_role:
        name: ibm_quarkus_beginner_workshop
      vars:
        ACTION: create
